module.exports = {
  FIELD_SIZE: 32,
  WORLD_WIDTH: 3200,
  WORLD_HEIGHT: 3200,
  DIRECTIONS: {
    EAST: [1, 0],
    NORTH: [0, -1],
    SOUTH: [0, 1],
    WEST: [-1, 0]
  },
  STARTING_BALANCE: 2000,
  BUILDING_COSTS: {
    CABLE: 1,
    HUB: 300,
    HOUSE: 0,
    DELETE: 1
  },
  HOUSE_SPAWN_COOLDOWN: -2,
  PROCEEDS_PER_HOUSEHOLD: 50,
  BASE_BANDWIDTH: 56,
  BANDWIDTH_PER_HUB: 300,
  DURATION_PER_DAY: 2000,
  POWER_CONSUMPTION_PER_HUB: 10,
  MAINTENANCE_COST: 10,
  REPAIR_COST: 50,
  HUB_WARRANTY: 30,
  HUB_DEFECT_RANGE: 1000,
  HUB_DESTROYED_CHANCE: 5,
  DAYS_TILL_CONTRACT_START: 14,
  MAX_HUB_RANGE: 20,
  HUB_STABLE_RANGE: 15,
  FINE: 50
}
